export const kintoneEvents = [
  'app.record.index.show',
  'app.record.index.edit.show',
  'app.record.index.edit.submit',
  'app.record.index.edit.submit.success',
  'app.record.index.delete.submit',
  'mobile.app.record.index.show',
  'app.record.detail.show',
  'app.record.detail.delete.submit',
  'app.record.detail.process.proceed',
  'mobile.app.record.detail.show',
  'mobile.app.record.detail.delete.submit',
  'mobile.record.detail.process.proceed',
  'app.record.create.show',
  'app.record.create.submit',
  'app.record.create.submit.success',
  'mobile.app.record.create.show',
  'mobile.app.record.create.submit',
  'mobile.app.record.create.submit.success',
  'app.record.edit.show',
  'app.record.edit.submit',
  'app.record.edit.submit.success',
  'mobile.app.record.edit.show',
  'mobile.app.record.edit.submit',
  'mobile.app.record.edit.submit.success',
  'app.record.print.show',
  'app.report.show',
  'mobile.app.report.show',
  'portal.show',
  'mobile.portal.show',
  'space.portal.show',
  'mobile.space.portal.show',
];

export const eventCategories = {
  list: ['app.record.index.show', 'mobile.app.record.index.show'],
  record: [
    'app.record.index.edit.show',
    'app.record.index.edit.submit',
    'app.record.index.edit.submit.success',
    'app.record.detail.show',
    'app.record.detail.delete.submit',
    'app.record.detail.process.proceed',
    'mobile.app.record.detail.show',
    'mobile.app.record.detail.delete.submit',
    'mobile.record.detail.process.proceed',
    'app.record.create.submit.success',
    'mobile.app.record.create.submit.success',
    'app.record.edit.show',
    'app.record.edit.submit',
    'app.record.edit.submit.success',
    'mobile.app.record.edit.show',
    'mobile.app.record.edit.submit',
    'mobile.app.record.edit.submit.success',
    'app.record.print.show',
  ],
  create: ['app.record.create.submit', 'mobile.app.record.create.submit'],
  createShow: ['app.record.create.show', 'mobile.app.record.create.show'],
  report: ['app.report.show', 'mobile.app.report.show'],
  portal: ['portal.show', 'mobile.portal.show'],
  spacePortal: ['space.portal.show', 'mobile.space.portal.show'],
};

export const excludeTypes = [
  'RECORD_NUMBER',
  'CREATOR',
  'CREATED_TIME',
  'MODIFIER',
  'UPDATED_TIME',
];
